FROM node:25 AS node-builder
WORKDIR /app
COPY ui ui
COPY Makefile Makefile
RUN make build-ui

FROM golang:1.25 AS go-builder
WORKDIR /go/src/github.com/rhobs/perses
COPY . .
COPY --from=node-builder /app/ui/app/dist ui/app/dist
RUN mkdir /perses \
  && mkdir /plugins \
  && make build-api \
  && make build-cli

FROM registry.access.redhat.com/ubi9/ubi-minimal

LABEL maintainer="The Perses Authors <perses-team@googlegroups.com>"
USER 0

COPY --from=go-builder                          /go/src/github.com/rhobs/perses/bin/perses        /bin/perses
COPY --from=go-builder                          /go/src/github.com/rhobs/perses/bin/percli        /bin/percli
COPY                                            LICENSE            /LICENSE
COPY --from=go-builder --chown=0:0  /go/src/github.com/rhobs/perses/plugins-archive/   /etc/perses/plugins-archive/
COPY                                            docs/examples/config.docker.yaml     /etc/perses/config.yaml
COPY --from=go-builder --chown=0:0  /perses            /perses
COPY --from=go-builder                          /plugins           /etc/perses/plugins
COPY --from=go-builder                          /etc/mime.types    /etc/mime.types
RUN chmod -R 0777 /etc/perses/plugins

WORKDIR /perses

EXPOSE     8080
VOLUME     ["/perses"]
ENTRYPOINT [ "/bin/perses" ]
CMD        ["--config=/etc/perses/config.yaml", \
            "--log.level=error"]
